# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'accudocs-backend'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  API_VERSION = 'v1'
  DB_DIALECT = 'sqlite'
  DB_STORAGE = '/data/database.sqlite'
  REDIS_ENABLED = 'false'
  LOG_LEVEL = 'info'
  LOG_DIR = '/data/logs'
  WHATSAPP_ENABLED = 'false'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'accudocs_data'
  destination = '/data'
